namespace MakeItSo {
	public static class UnityEditorCommands {
		public static string[] AllCLIArguments => new string[] {
			"-accept-apiupdate",
			"-batchmode",
			"-buildLinux64Player <pathname>",
			"-buildOSXUniversalPlayer <pathname>",
			"-buildTarget <name>",
			"-buildWindowsPlayer <pathname>",
			"-buildWindows64Player <pathname>",
			"-createProject <pathname>",
			"-deepprofiling",
			"-disable-assembly-updater <assembly1 assembly2>",
			"-diag-debug-shader-compiler",
			"-enableCodeCoverage",
			"-executeMethod <ClassName.MethodName>",
			"-executeMethod <NamespaceName.ClassName.MethodName>",
			"-exportPackage <exportAssetPath1 exportAssetPath2 ExportAssetPath3 exportFileName>",
			"-force-d3d11",
			"-force-d3d12",
			"-force-device-index",
			"-force-metal",
			"-force-glcore",
			"-force-glcoreXY",
			"-force-gles",
			"-force-glesXY",
			"-force-vulkan",
			"-force-clamped",
			"-force-free",
			"-force-low-power-device",
			"-importPackage <pathname>",
			"-job-worker-count <N>",
			"-logFile <pathname>",
			"-nographics",
			"-noUpm",
			"-openfile <path>",
			"-password <password>",
			"-profiler-enable",
			"-profiler-log-file <Path/To/Log/File.raw>",
			"-profiler-capture-frame-count <NumberOfFrames>",
			"-profiler-maxusedmemory",
			"-projectPath <pathname>",
			"-quit",
			"-returnlicense",
			"-serial <serial>",
			"-setDefaultPlatformTextureFormat",
			"-silent-crashes",
			"-stackTraceLogType <type>",
			"-testPlatform",
			"-testResults",
			"-runTests",
			"-username <username>",
			"-vcsMode <mode>",
			"-EnableCacheServer",
			"-cacheServerEndpoint <endpoint>",
			"-cacheServerNamespacePrefix <prefix>",
			"-cacheServerEnableDownload <enabled>",
			"-cacheServerEnableUpload <enabled",
			"-CacheServerIPAddress <host:port>"
		};
	}
}
